title: Curation.LA
author: Darren

description: >
  software, tech, LA.

show_excerpts: true

minima:
  social_links:
    twitter: darrenaalfonso

twitter_username: darrenaalfonso

theme: minima

plugins:
  - jekyll-feed
